name: Backend workflow

env:
  IMAGE_TAG: ${{ github.sha }}

on: workflow_dispatch

jobs:
  Push-of-Docker-Image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build of docker image
        run : |
          docker build -t terezabisharyan/app-server:$IMAGE_TAG ./server/

      - name: Push image on DockerHub
        run : |
          docker login -u terezabisharyan -p ${{ secrets.DOCKER_PASSWORD }}
          docker push terezabisharyan/app-server:$IMAGE_TAG
